[package]
name = "k8s-dns-api"
version = "0.1.0"
authors = ["Mike Cronce <mc@planetscale.com>"]
edition = "2018"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "thin"
debug = false

[dependencies]
actix-files = "~0.2"
actix-rt = "~1"
actix-web = "~2"
env_logger = "~0.7"
kube = {version = "~0.25", features = ["openapi"]}
k8s-openapi = {version = "~0.7", default-features = false, features = ["v1_15"]}
actix-helper-macros = "~0.2"

